services:
  - type: web
    name: celebrity-styles-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /api/health

  - type: web
    name: celebrity-styles-frontend
    env: static
    plan: free
    buildCommand: echo "Static site - no build required"
    staticPublishPath: ./frontend
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 